### ISSUE TITLE
Will you share the code?

### ISSUE THREAD

**Issue by GoingMyWay** [atavakol/action-hypergraph-networks#1]
Dear authors,

Will you plan to share the code?

**Comment by atavakol** [comment]
Hi Alexander! We plan to release the code in early May.

**Comment by GoingMyWay** [comment]
> Hi Alexander! We plan to release the code in early May.

Great, thank you for your reply.

**Comment by atavakol** [comment]
@GoingMyWay With much delay, the code is now live! Let me know if you have any questions. :)

**Comment by GoingMyWay** [comment]
> @GoingMyWay With much delay, the code is now live! Let me know if you have any questions. :)

That's awesome!!!
